"""Tests for `GET /api/server/info` (wrapper self-heal scheme discovery).

The endpoint is the source of truth for the orchestrator's current
scheme + public origin. Wrappers call it (over plain HTTP or HTTPS,
whichever they already have configured) to learn what URL to use
going forward. The response shape is intentionally narrow:

    {
      "scheme": "http" | "https",
      "public_origin": "scheme://host:port",   // bare, no path
      "cert_fingerprint_sha256": "..." | ""   // empty if scheme=http
    }

No auth. The endpoint exposes no secrets -- the URL is already
public (anyone who can reach the port can learn whether it's TLS).
The fingerprint lets a future v0.7.3-style pinning implementation
read the cert thumbprint from the same endpoint instead of a
second round-trip.
"""
from __future__ import annotations

import os
import sys
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

# Allow tests to import from src
sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from hermes_orch import db as db_mod
from hermes_orch.main import create_app


@pytest.fixture
def client_http(tmp_path, monkeypatch):
    """TestClient with the orchestrator configured for plain HTTP."""
    # conftest.py sets HERMES_ORCH_PUBLIC_ORIGIN session-wide to
    # `http://127.0.0.1:8765`, and the env var wins over the config
    # file. For these tests we want the config file to be the source
    # of truth, so clear the env var first.
    monkeypatch.delenv("HERMES_ORCH_PUBLIC_ORIGIN", raising=False)

    cfg_path = tmp_path / "config.yaml"
    cfg_path.write_text(
        "orchestrator:\n  port: 18765\n  bind_host: 127.0.0.1\n"
        "server:\n  public_origin: 'http://hermes-win:8765'\n"
        "https:\n  enabled: false\n  ssl_cert_path: ''\n  ssl_key_path: ''\n",
        encoding="utf-8",
    )
    monkeypatch.setenv("HERMES_ORCH_CONFIG", str(cfg_path))

    test_db = tmp_path / "test_server_info.db"
    orig_db_init = db_mod.Database.__init__

    def patched_db_init(self, db_path):
        orig_db_init(self, test_db)

    monkeypatch.setattr(db_mod.Database, "__init__", patched_db_init)
    app = create_app()
    with TestClient(app) as c:
        yield c


@pytest.fixture
def client_https(tmp_path, monkeypatch):
    """TestClient with the orchestrator configured for HTTPS + a real cert.

    We use a self-signed cert generated by `cryptography` (already a
    project dep). The fingerprint must match the SHA-256 of the cert
    DER bytes -- NOT `GetCertHash()` (which is the Microsoft-specific
    thumbprint with a different algorithm).
    """
    try:
        from cryptography import x509
        from cryptography.x509.oid import NameOID
        from cryptography.hazmat.primitives import hashes, serialization
        from cryptography.hazmat.primitives.asymmetric import rsa
        import datetime as _dt
    except ImportError:
        pytest.skip("cryptography not available")

    # Generate a fresh self-signed cert
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    subject = issuer = x509.Name([
        x509.NameAttribute(NameOID.COMMON_NAME, "hermes-test"),
    ])
    cert = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(issuer)
        .public_key(key.public_key())
        .serial_number(x509.random_serial_number())
        .not_valid_before(_dt.datetime.utcnow() - _dt.timedelta(minutes=1))
        .not_valid_after(_dt.datetime.utcnow() + _dt.timedelta(days=365))
        .sign(key, hashes.SHA256())
    )
    cert_path = tmp_path / "test.crt"
    key_path = tmp_path / "test.key"
    cert_path.write_bytes(cert.public_bytes(serialization.Encoding.PEM))
    key_path.write_bytes(
        key.private_bytes(
            encoding=serialization.Encoding.PEM,
            format=serialization.PrivateFormat.TraditionalOpenSSL,
            encryption_algorithm=serialization.NoEncryption(),
        )
    )

    cfg_path = tmp_path / "config.yaml"
    cfg_path.write_text(
        f"orchestrator:\n  port: 18765\n  bind_host: 127.0.0.1\n"
        f"server:\n  public_origin: 'https://hermes-win:8765'\n"
        f"https:\n  enabled: true\n  ssl_cert_path: '{cert_path.as_posix()}'\n  ssl_key_path: '{key_path.as_posix()}'\n",
        encoding="utf-8",
    )
    # Drop the session-wide HERMES_ORCH_PUBLIC_ORIGIN so the config
    # file is the source of truth (env var wins otherwise).
    monkeypatch.delenv("HERMES_ORCH_PUBLIC_ORIGIN", raising=False)
    monkeypatch.setenv("HERMES_ORCH_CONFIG", str(cfg_path))

    test_db = tmp_path / "test_server_info_https.db"
    orig_db_init = db_mod.Database.__init__

    def patched_db_init(self, db_path):
        orig_db_init(self, test_db)

    monkeypatch.setattr(db_mod.Database, "__init__", patched_db_init)
    app = create_app()
    with TestClient(app) as c:
        yield c, cert.public_bytes(serialization.Encoding.DER)


# ===== endpoint exists + is unauth =====

def test_server_info_endpoint_exists_and_is_unauth(client_http):
    """The endpoint must be reachable without any auth headers."""
    r = client_http.get("/api/server/info")
    assert r.status_code == 200, r.text
    body = r.json()
    # required keys
    for k in ("scheme", "public_origin", "cert_fingerprint_sha256"):
        assert k in body, f"missing key {k!r} in response: {body}"


# ===== HTTP server: scheme=http, empty fingerprint =====

def test_server_info_http_scheme(client_http):
    r = client_http.get("/api/server/info")
    assert r.status_code == 200
    body = r.json()
    assert body["scheme"] == "http"
    assert body["public_origin"] == "http://hermes-win:8765"
    assert body["cert_fingerprint_sha256"] == ""


# ===== HTTPS server: scheme=https, real cert fingerprint =====

def test_server_info_https_scheme_and_fingerprint(client_https):
    c, der_bytes = client_https
    r = c.get("/api/server/info")
    assert r.status_code == 200
    body = r.json()
    assert body["scheme"] == "https"
    assert body["public_origin"] == "https://hermes-win:8765"
    # SHA-256 of the cert DER bytes -- lower-case hex, 64 chars
    import hashlib
    expected = hashlib.sha256(der_bytes).hexdigest()
    assert body["cert_fingerprint_sha256"] == expected
    assert len(body["cert_fingerprint_sha256"]) == 64
    # The response should be stable across two calls (no nonces, no
    # random data)
    r2 = c.get("/api/server/info")
    assert r2.json() == body
