#!/usr/bin/env python3
"""Hermes Orchestrator watchdog (Linux) — analogue to watchdog-hermes.ps1.

Polled by systemd every 1 minute (via the .timer unit generated by
install-systemd.sh). If port 8765 isn't listening, start the server
in the background. Mirrors the Windows PS1 behavior:

  - check port 8765
  - if listening, exit
  - if not, spawn `python -m hermes_orch serve --no-reload`
  - log to watchdog-hermes.log (with 200KB rotation)
  - support `restart-now` flag file for manual force-restart

Cross-platform notes:
  - On Linux this is invoked by systemd timer. systemd itself
    restarts the main service on crash (Restart=on-failure), so
    this watchdog is a fallback for cases where the service is
    "active" but the port is dead (e.g. stuck worker, or a
    crash that systemd hasn't noticed yet).
  - On Windows, watchdog-hermes.ps1 is the equivalent. That one
    needs the explicit "USERPROFILE = C:\\Users\\..." workaround
    because Task Scheduler runs the watchdog in session 0, but
    this Python script inherits whatever the systemd env set up —
    no fixup needed (USER is set by systemd user instance).
  - The `restart-now` flag is a cross-OS pattern: write a file,
    watchdog on next tick notices + force-restarts. Works on
    both Windows and Linux. Same semantics.
  - The PS1 logs a single line per tick. This Python script does
    the same but with cleaner log rotation (rename to
    watchdog-hermes-<timestamp>.log when over 200KB, just like
    the PS1) so ops scripts that parse the log don't break.

This script is a pure cross-platform module (no Windows-specific
imports). On Windows it can be invoked by Task Scheduler as a
fallback to the PS1 (see the Windows install spec for the PS1
path); the Python implementation here is Linux-only in practice
because install-systemd.sh is the documented install path on Linux.
"""
from __future__ import annotations

import errno
import os
import signal
import socket
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

# ---- Configuration (resolved from env or relative to this script) ----
PORT = int(os.environ.get("HERMES_WATCHDOG_PORT", "8765"))
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = Path(os.environ.get("HERMES_PROJECT_DIR", SCRIPT_DIR.parent))
PYTHON_EXE = Path(
    os.environ.get("HERMES_PYTHON", PROJECT_DIR / ".venv" / "bin" / "python")
)
WATCHDOG_DIR = SCRIPT_DIR
LOG_FILE = WATCHDOG_DIR / "watchdog-hermes.log"
STDOUT_LOG = WATCHDOG_DIR / "server.stdout.log"
STDERR_LOG = WATCHDOG_DIR / "server.stderr.log"
RESTART_FLAG = WATCHDOG_DIR / "restart-now"
MAX_LOG_BYTES = 200 * 1024  # 200KB, matches the PS1

# ---- Logging (with 200KB rotation, matches PS1 behavior) ----

def _rotate_if_needed() -> None:
    """Rename the log to a timestamped sibling if it has grown past 200KB.

    Same convention as the PS1: keeps ops scripts that tail the log
    (and tools that grep for a single line per tick) working without
    having to handle multiple open files. Old rotated logs are NOT
    deleted by this script — they're tiny and easy to spot for
    humans; if disk pressure ever becomes an issue, add a
    logrotate.d rule.
    """
    try:
        if LOG_FILE.exists() and LOG_FILE.stat().st_size > MAX_LOG_BYTES:
            stamp = datetime.now().strftime("%Y%m%d-%H%M%S")
            LOG_FILE.rename(WATCHDOG_DIR / f"watchdog-hermes-{stamp}.log")
    except OSError:
        # Rename failed (e.g. permission); continue with the existing
        # log file rather than blocking the watchdog. Worst case
        # the log grows unbounded until next manual cleanup.
        pass

def log(msg: str) -> None:
    """Append a single timestamped line to the watchdog log.

    Per-tick writes only — the watchdog runs once a minute so the
    log grows at most ~1 line/min. At 80 chars/line that's
    ~115KB/day, well under the 200KB cap that triggers rotation.
    """
    _rotate_if_needed()
    line = f"{datetime.now().strftime('%Y-%m-%d %H:%M:%S')} {msg}\n"
    try:
        with LOG_FILE.open("a", encoding="utf-8") as f:
            f.write(line)
    except OSError:
        # Don't raise from logging — a log-write failure should
        # not break the watchdog.
        pass

# ---- Port + process helpers ----

def is_port_listening() -> bool:
    """Return True if something on localhost is listening on PORT.

    Uses connect_ex() rather than bind() because we want a
    *non-invasive* check (don't try to take the port ourselves).
    connect_ex returns 0 on success, errno.ECONNREFUSED (or other
    "no listener") otherwise. We also accept the connection then
    close it immediately so we don't keep an open socket in CLOSE_WAIT.
    """
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.settimeout(1.0)
            rc = s.connect_ex(("127.0.0.1", PORT))
            return rc == 0
    except OSError:
        return False

def find_pid_listening_on_port() -> int | None:
    """Return PID of the process listening on PORT, or None.

    Cross-platform attempt: try `lsof` first, fall back to `ss`,
    fall back to `fuser`. These are the standard Linux tools; we
    don't try Windows here because this script is Linux-only by
    convention (PS1 is the Windows path). If none of the tools
    are available, return None and let the caller fall back to
    `pkill -f "hermes_orch serve"` for a cruder kill.
    """
    # 1) lsof -t -i :PORT -sTCP:LISTEN
    try:
        out = subprocess.check_output(
            ["lsof", "-t", f"-i:{PORT}", "-sTCP:LISTEN"],
            stderr=subprocess.DEVNULL, timeout=3,
        ).decode().strip()
        if out:
            return int(out.splitlines()[0])
    except (subprocess.CalledProcessError, FileNotFoundError, ValueError):
        pass
    # 2) ss -tlnp 'sport = :PORT' (parse "pid=NNNN,")
    try:
        out = subprocess.check_output(
            ["ss", "-tlnp", f"sport = :{PORT}"],
            stderr=subprocess.DEVNULL, timeout=3,
        ).decode()
        for line in out.splitlines()[1:]:  # skip header
            if "pid=" in line:
                # pid=1234,fd=...  OR  users:(("python",pid=1234,fd=...))
                seg = line.split("pid=")[1]
                digits = ""
                for ch in seg:
                    if ch.isdigit():
                        digits += ch
                    else:
                        break
                if digits:
                    return int(digits)
    except (subprocess.CalledProcessError, FileNotFoundError, ValueError):
        pass
    # 3) fuser PORT/tcp
    try:
        out = subprocess.check_output(
            ["fuser", f"{PORT}/tcp"],
            stderr=subprocess.STDOUT, timeout=3,
        ).decode().strip()
        if out:
            return int(out.split()[-1])
    except (subprocess.CalledProcessError, FileNotFoundError, ValueError):
        pass
    return None

def kill_existing_server() -> None:
    """SIGTERM the PID listening on PORT, escalate to SIGKILL after 5s.

    Mirrors the PS1's Stop-Process -Force pattern but uses POSIX
    signals. The escalation timeout is shorter than the systemd
    default (90s) because we want a fast restart for the watchdog
    fallback path.
    """
    pid = find_pid_listening_on_port()
    if pid is None:
        # Last resort: pkill the server. Less precise (could hit
        # a different python process) but covers the case where
        # all 3 port-introspection tools above are missing.
        try:
            subprocess.run(
                ["pkill", "-f", "hermes_orch serve"],
                timeout=3, check=False,
            )
        except FileNotFoundError:
            pass
        return
    try:
        os.kill(pid, signal.SIGTERM)
        log(f"[KILL] sent SIGTERM to PID {pid}")
    except ProcessLookupError:
        log(f"[KILL] PID {pid} already gone")
        return
    # Wait up to 5s for the process to exit
    for _ in range(50):
        time.sleep(0.1)
        try:
            os.kill(pid, 0)  # signal 0 = existence check, no actual signal
        except ProcessLookupError:
            log(f"[KILL] PID {pid} exited after SIGTERM")
            return
    # Still alive — SIGKILL
    try:
        os.kill(pid, signal.SIGKILL)
        log(f"[KILL] SIGKILL to PID {pid} (SIGTERM timed out)")
    except ProcessLookupError:
        pass

# ---- Server launch ----

def start_server() -> int:
    """Launch the server in a detached process. Returns the new PID.

    The Popen call uses start_new_session=True so the server is
    in its own process group — if the watchdog is invoked by
    systemd and systemd kills it for any reason, the server
    keeps running (otherwise SIGTERM to the watchdog's pgroup
    would cascade). stdout/stderr are appended (not truncated)
    to the same files the PS1 wrote to, so ops scripts that
    tail those files still work.
    """
    if not PYTHON_EXE.exists():
        log(f"[ERROR] python not found at {PYTHON_EXE}")
        log(f"[ERROR] set HERMES_PYTHON env var to point at the right venv")
        return 0
    # Open log files in append-binary mode; Popen doesn't accept
    # text mode cross-platform, and we want the same byte-level
    # append as the PS1's Out-File -Append.
    stdout_fp = STDOUT_LOG.open("ab")
    stderr_fp = STDERR_LOG.open("ab")
    try:
        proc = subprocess.Popen(
            [str(PYTHON_EXE), "-m", "hermes_orch", "serve", "--no-reload"],
            cwd=str(PROJECT_DIR),
            stdout=stdout_fp,
            stderr=stderr_fp,
            stdin=subprocess.DEVNULL,
            start_new_session=True,
        )
    finally:
        stdout_fp.close()
        stderr_fp.close()
    return proc.pid

# ---- Main ----

def main() -> int:
    # 1) Force-restart flag: if the file exists, consume it and
    #    always restart, even if the port is currently listening.
    #    This is the manual escape hatch ("I just want a fresh
    #    server"). Same semantics as the PS1.
    force_restart = RESTART_FLAG.exists()
    if force_restart:
        try:
            RESTART_FLAG.unlink()
        except OSError:
            pass
        log("[FORCE] restart-now flag found, killing existing server")

    # 2) Port check
    if is_port_listening() and not force_restart:
        log(f"[OK] port {PORT} listening")
        return 0

    # 3) If force-restart and listening: kill the existing process
    if force_restart:
        kill_existing_server()
        # Give the OS a beat to release the port
        time.sleep(2)

    # 4) Server is down (or force-restart in progress). Start it.
    log(f"[DOWN] port {PORT} NOT listening, launching server...")
    pid = start_server()
    if pid == 0:
        log("[ERROR] failed to start (see prior log lines for cause)")
        return 1

    # 5) Verify the port actually came up. The server can take
    #    a few seconds (DB init, fork workers). The PS1 used
    #    2s, which is enough for a warm restart; for cold
    #    first-launch this might race, but the systemd main
    #    service has its own Restart=on-failure so a failed
    #    boot here will get a second chance.
    time.sleep(2)
    if is_port_listening():
        log(f"[UP] server up (PID {pid}, port {PORT} listening)")
    else:
        log(f"[WARN] launched PID {pid} but port {PORT} still not listening after 2s (systemd will retry)")
    return 0

if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as e:
        # Last-ditch: log the exception and exit non-zero so
        # systemd's OnFailure= can fire if the watchdog itself
        # is broken (separate service).
        log(f"[CRASH] watchdog exception: {type(e).__name__}: {e}")
        sys.exit(1)
